from rich.console import Console
from rich.text import Text

console = Console()
text = Text()
# Append a raw string (r"…") to the Text object with a specific color style.
# The 'r' before the string makes it a raw string literal (backslashes are not treated as escape characters).
text.append(r"           /                  :^          \     ", style="#df8e49")
text.append("\n")
text.append(r"         /                  .:.~      !     \ ", style="#df8e49")
console.print(text)
print ("         /                  .:.~      !     \   ")
print ("        /            .   .:^:  ~     ^ ^.     ~~  ")
print ("       |            .!. .^^....~   .~  .~  :   ^~ ")
print ("      |            :!: :^.    :^  .^ ...! .7    ^^")
print ("      |     .:.  ::::^~^:!7 ^ ^. :      : :J.    ?")
print ("      |    ::.:.:. :    ?^.!?:^.::  .::..~^!:    |")
print ("      .   ..^~:.   |   Y.  ~?       7?!7^?:::    !")
print ("       . .. :~ ...     ?   Y^      ^   ?^:^:^    ~")
print ("      ....     :^^^:   ?  7~       5   J..~^  ~^ ")
print ("     .:  ::.^    ...    -          J   ! ^:! !  ")
print ("    ..    ..~                       !~^   ~!..    ")
print ("..::..      ^:                        .^^~7:      ")
print (".:::^~  ..  .~^    \                   .:7:      ") 
print (" .::...:^.  .:?^.   ^:........        .~        ")
print ("    .~J!. .:^^:^~~                    .^7:        ")
print ("  .:7&@GP!:    .::^~!7^:....^:.     ::^:          ")
print (".::. ^5@@@&GY7!^^~!??~.~...::::::...              ")
print (":      :75B&@@@@@@@@@B!:                          ")
print ("          .:~~!777!!!!7~                          ")
print ("            ...........:^                         ")
print ("                 ..     ^.                        ")
print ("               /        :~                        ")
print ("              :         :~                        ")
print ("             /          ~:                        ")
print ("            ^           !                         ")
