print ("GP555PPBB5GBPY5555B&5P555555P5555555PPGY!5&G~.           .  ")
print ("5555Y^?#&&5Y5YYY5YB@G5555555PBG55PGP5?:    :?57.         .  ")
print ("55YYY5GY#7 .?5YY55B&@#55PPPPPG&#Y?7^          YGJ:          ")
print ("Y55YP&55GJ .?5J.^P&G&##J7!~~:: 77          .!Y55G#5^        ")
print ("5555&G555@#5P55?JB&#? YB^..... .P5:.::!!7Y5P55###PPGP!.    .")
print ("55Y5&555G@@#5PP55###   :&&G#&&&&&@@#&GPPPPPPPPP#&&&#BBB7.   ")
print ("P55Y&BY5&&^GB5555#&G  .Y@@@@&&##BB@@&&BBPPPPPPPG&#@P?G#BBJ. ")
print ("5B#@#&&&@5  J#P55B&G.5#P!.7@@###BGB@@&#PPPP5PPGPG&#&. :!G##J")
print ("5B@G.5&&@BGJ ~#GYP@#:.   J&&B&@@@@@@&B@BPP5PPPPB5B&&P.   .~5")
print ("B@B~#&#@@G77.  JGP&@    ?&~ :BG55?Y&@&@&PGPPPGPB&P&#&!!!    ")
print ("&#.5&.:#P5BJ    :YG@~   5. .&P557  .&@@@PPGPPPP5&#G&#^ ~7   ")
print ("@! G! PG7  P!     .?Y      !&5555!..P&J@P5PPPPPPB@B&&Y :J   ")
print ("Y^ :7 PG5J!GG              ?@5PPPPP5##.@GPPPPPPPG@&B&G~@Y  .")
print ("  ~ . ^#5P5GG              .@GPP5PPG@^ &GPPPPPPPP@@&@@@B&?P&")
print ("J !    YGPP&B               Y@&####@? ^&5PPPPPPG&G~:~G&GG@G ")
print ("BG&~   .GBGP:                .^~~~:.  5#PPPPPPP@5     !&GBG.")
print ("PPB&:            .!~^::~?             &P5PGPPB@&       &BBB#")
print ("PP5B#5^           5B:...^J           7#5PPPG#@@:      ?B75PB")
print ("PP5P5GBGP!:        !!.   ^7       .~5&PPPBG!!&~      :~     ")
print ("PPG&&GPPGGB#BY7^..  ^?!^~5~ ..^75J!!&BG&&B7^7:     .Y#!     ")
print ("BPB~Y#&#P5#P?P#B&77B7!J?7~:::~7!P7:G@&&P~:~7:    .^:.:7P.   ")
print ("@&:   ^Y##&    .7!7J^^^~~~^?G&J^:^#@&!:~~^.      !.    !P   ")
print ("JG.      .. J7^PY        .5&Y.:7!J&B7^:         7.     YG!. ")
print (" .P^~~~~^:^BB. 7J~7~~7^ ~#G^ :#.               7^     ~7 :G:")
print (" .7    ^Y?G#^..!&Y .7P^5@Y:  !@.       :Y.     77   .7:   ?^")
print (" ^!  ::.  #B&PP5J!^!!  ?@Y#YPGYJ7!~7JYG#&B~..   ~77#7    ~B ")
print (" 7! :~^::?YP5!~^:.:.   7GY#J:     :&@&BGGB##BBP.   J@5YY7:#:")
print ("  BYBGB@BB~:.    .    .?J!      .!B&&@@#&###&&&#J^:~&G^..!! ")
print ("B5::5&G?7^     .. .B#7P7#&.   5       :G:!  ?~.             ")
